; Inventaire pour la PRÉPARATION des hôtes (avant Kolla).
; Adapter les IPs avec les valeurs réelles du subnet mgmt.

[nodes]
node1 ansible_host=10.0.1.11 vip_holder=true
node2 ansible_host=10.0.1.12
node3 ansible_host=10.0.1.13

[nodes:vars]
ansible_user=ubuntu
ansible_python_interpreter=/usr/bin/python3
